/**
 * 🛡️ AIGatekeeper Core — MetadataSanitizer Implementation
 *
 * Implementación con re2 (Google Regex) para seguridad contra
 * catastrophic backtracking (ReDoS) en código no confiable.
 *
 * Todos los patrones se compilan UNA VEZ en el constructor.
 * Sanitize() es thread-safe (no muta el estado del objeto).
 */

#include "sanitizer.h"
#include <re2/re2.h>
#include <algorithm>
#include <cassert>

namespace aigatekeeper {

// ============================================================================
// PIMPL — oculta re2 del header
// ============================================================================

class MetadataSanitizer::Impl {
public:
    std::unique_ptr<re2::RE2> absolute_path_re_;
    std::vector<std::unique_ptr<re2::RE2>> ai_comment_patterns_;
    std::vector<std::unique_ptr<re2::RE2>> session_token_patterns_;
    std::vector<std::unique_ptr<re2::RE2>> model_signatures_;

    Impl();
};

// ============================================================================
// Helpers para crear opciones de re2
// ============================================================================

static re2::RE2::Options ci_opts() {
    re2::RE2::Options opts;
    opts.set_case_sensitive(false);
    opts.set_log_errors(false);
    return opts;
}

static re2::RE2::Options ci_dotnl_opts() {
    re2::RE2::Options opts = ci_opts();
    opts.set_dot_nl(true);
    return opts;
}

// ============================================================================
// Constructor del Impl — compila todos los patrones UNA VEZ
// ============================================================================

MetadataSanitizer::Impl::Impl()
    : absolute_path_re_(std::make_unique<re2::RE2>(
          R"((?:[A-Za-z]:\\|/home/|/Users/|/root/|C:/|D:/|E:/)(?:[a-zA-Z0-9_.\-]+[/\\])*([a-zA-Z0-9_.\-]+))",
          re2::RE2::Quiet
      ))
{
    // -- Comentarios de IA (case-insensitive) --
    ai_comment_patterns_.push_back(std::make_unique<re2::RE2>(
        R"(//\s*(?:THINKING|Thought|Reasoning)[:\s].*)", ci_opts()));
    ai_comment_patterns_.push_back(std::make_unique<re2::RE2>(
        R"(//\s*Generated by\s+.*)", ci_opts()));
    ai_comment_patterns_.push_back(std::make_unique<re2::RE2>(
        R"(#\s*(?:THINKING|Thought|Reasoning)[:\s].*)", ci_opts()));
    ai_comment_patterns_.push_back(std::make_unique<re2::RE2>(
        R"(""".*?(?:AI|Model|Generated).*?""")", ci_dotnl_opts()));
    ai_comment_patterns_.push_back(std::make_unique<re2::RE2>(
        R"('''.*?(?:AI|Model|Generated).*?''')", ci_dotnl_opts()));

    // -- IDs de sesión y tokens --
    session_token_patterns_.push_back(std::make_unique<re2::RE2>(
        R"(session[_-]?id["']?\s*[:=]\s*["'][a-zA-Z0-9-]+["'])", ci_opts()));
    session_token_patterns_.push_back(std::make_unique<re2::RE2>(
        R"(model[_-]?id["']?\s*[:=]\s*["'][a-zA-Z0-9-_:.-]+["'])", ci_opts()));
    session_token_patterns_.push_back(std::make_unique<re2::RE2>(
        R"(trace[_-]?id["']?\s*[:=]\s*["'][a-zA-Z0-9-]+["'])", ci_opts()));

    // -- Firmas de modelos de IA --
    model_signatures_.push_back(std::make_unique<re2::RE2>(
        R"(claude[_-]?code)", ci_opts()));
    model_signatures_.push_back(std::make_unique<re2::RE2>(
        R"(open[_-]?code)", ci_opts()));
    model_signatures_.push_back(std::make_unique<re2::RE2>(
        R"(gpt[_-]?(?:3\.5|4|4[_-]?turbo))", ci_opts()));
    model_signatures_.push_back(std::make_unique<re2::RE2>(
        R"( anthropic)", ci_opts()));
}

// ============================================================================
// Constructor/Destructor público
// ============================================================================

MetadataSanitizer::MetadataSanitizer()
    : pimpl_(std::make_unique<Impl>())
{}

MetadataSanitizer::~MetadataSanitizer() = default;

// ============================================================================
// Helpers — usan re2::StringPiece como match (NO std::string)
// para evitar sobrecarga template que no recolecta correctamente.
// ============================================================================

namespace {

void find_and_replace(
    std::string& code,
    const re2::RE2& pattern,
    std::string_view replacement,
    std::string_view label,
    std::vector<std::pair<std::string, std::string>>& removed
) {
    // 1. Recolectar matches usando Match()
    //    NOTA: FindAndConsume() está roto en esta versión de re2 (2025.11.05-3).
    //    Match() + avance manual es el workaround.
    {
        re2::StringPiece input(code);
        re2::StringPiece match;
        size_t pos = 0;
        while (pos < input.size()) {
            if (pattern.Match(input, pos, input.size(), re2::RE2::UNANCHORED,
                              &match, 1)) {
                removed.emplace_back(label,
                                     std::string(match.data(), match.size()));
                pos = (match.data() - input.data()) + match.size();
                if (match.size() == 0) ++pos;  // evitar loop infinito
            } else {
                break;
            }
        }
    }
    // 2. Reemplazar globalmente
    re2::RE2::GlobalReplace(&code, pattern, replacement);
}

void apply_patterns(
    std::string& code,
    const std::vector<std::unique_ptr<re2::RE2>>& patterns,
    std::string_view replacement,
    std::string_view label,
    std::vector<std::pair<std::string, std::string>>& removed
) {
    for (const auto& pattern : patterns) {
        find_and_replace(code, *pattern, replacement, label, removed);
    }
}

}  // anonymous namespace

// ============================================================================
// Sanitize — pipeline principal
// ============================================================================

SanitizeResult MetadataSanitizer::sanitize(std::string_view code) const {
    auto& impl = *pimpl_;

    std::string cleaned(code);
    std::vector<std::pair<std::string, std::string>> removed;

    // -- Paso 1: Rutas absolutas --
    {
        re2::StringPiece input(cleaned);
        re2::StringPiece match;
        size_t pos = 0;
        while (pos < input.size()) {
            if (impl.absolute_path_re_->Match(input, pos, input.size(),
                    re2::RE2::UNANCHORED, &match, 1)) {
                removed.emplace_back("absolute_path",
                                     std::string(match.data(), match.size()));
                pos = (match.data() - input.data()) + match.size();
                if (match.size() == 0) ++pos;
            } else {
                break;
            }
        }
        re2::RE2::GlobalReplace(&cleaned, *impl.absolute_path_re_, "./\\1");
    }

    // -- Paso 2: Comentarios de IA --
    apply_patterns(cleaned, impl.ai_comment_patterns_, "", "ai_comment", removed);

    // -- Paso 3: Tokens y session IDs --
    apply_patterns(cleaned, impl.session_token_patterns_, "[REDACTED]", "session_token", removed);

    // -- Paso 4: Firmas de modelos --
    apply_patterns(cleaned, impl.model_signatures_, "[MODEL]", "model_signature", removed);

    return SanitizeResult{
        .cleaned_code = std::move(cleaned),
        .removed_items = std::move(removed)
    };
}

// ============================================================================
// Free function (singleton perezoso thread-safe C++11+)
// ============================================================================

std::string sanitize_code(std::string_view code) {
    static const MetadataSanitizer sanitizer;
    return sanitizer.sanitize(code).cleaned_code;
}

}  // namespace aigatekeeper
